version: '3.9'
services:
  php:
    build: ./php-fpm
    volumes:
      - .:/var/www/html
      - ./logs:/var/www/html/logs
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html:ro
      - ./logs:/var/www/html/logs
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${PORT}:80
